# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# This pipeline will be extended to the MicroBuild template
# The Task 'PublishBuildArtifacts@1' has been converted to an output named 'Publish Artifact: IIS Administration' in the templateContext section.
# The Task 'PublishBuildArtifacts@1' has been converted to an output named 'Publish Artifact: IISAdministrationSetup' in the templateContext section.
# The Task 'PublishBuildArtifacts@1' has been converted to an output named 'Publish Artifact: IISAdministrationSetup MSI' in the templateContext section.
# The Task 'PublishBuildArtifacts@1' has been converted to an output named 'Publish Artifact: Symbols' in the templateContext section.
trigger:
  branches:
    include:
    - releases/*
    exclude:
    - releases/old*
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/dev
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
variables:
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu
- name: Codeql.Enabled
  value: true
- name: SetupBuild.DefinitionId
  value: 6773
- name: SigningIdentity
  value: 400
- name: SignType
  value: Real
- name: TeamName
  value: IISAdmin
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
    pool:
      name: AzurePipelines-EO
      image: AzurePipelinesWindows2022compliantGPT
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: Phase_1
        displayName: Phase 1
        timeoutInMinutes: 0
        cancelTimeoutInMinutes: 1
        pool:
          name: VSEngSS-MicroBuild2022-1ES
          demands:
          - MSBuild_15.0_x64
          - MSBuild_15.0
        templateContext:
          mb:
            signing:
              enabled: true
              signType: $(SignType)
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish Artifact: IIS Administration'
            targetPath: $(Build.SourcesDirectory)/dist
            artifactName: IIS.Administration
          - output: pipelineArtifact
            displayName: 'Publish Artifact: IISAdministrationSetup'
            targetPath: $(Build.SourcesDirectory)/installer/IISAdministrationBundle/bin/x64/Release
            artifactName: IISAdministrationSetup
          - output: pipelineArtifact
            displayName: 'Publish Artifact: IISAdministrationSetup MSI'
            targetPath: installer/IISAdministrationSetup/bin
            artifactName: IISAdministrationSetup-MSI
          - output: pipelineArtifact
            displayName: 'Publish Artifact: Symbols'
            targetPath: $(Build.SourcesDirectory)/dist/symbols
            artifactName: symbols
        steps:
        - checkout: self
          fetchTags: false
          persistCredentials: True
        - task: UseDotNet@2
          displayName: Use .NET Core sdk
          inputs:
            version: 6.0.111
        - task: CmdLine@2
          displayName: Delete all obj and bin folders
          inputs:
            script: |
              for /d /r . %%d in (bin,obj) do @if exist "%%d" rd /s/q "%%d"
            workingDirectory: src
          continueOnError: true
        - task: NuGetToolInstaller@1
          displayName: Use NuGet >=4.7.1
          inputs:
            versionSpec: '>=4.7.1'
        - task: NuGetCommand@2
          displayName: NuGet restore
          inputs:
            solution: Microsoft.IIS.Administration.sln
        - task: MSBuild@1
          displayName: Build IIS Administration
          inputs:
            solution: Microsoft.IIS.Administration.sln
            msbuildVersion: 17.0
            msbuildArchitecture: x64
            configuration: $(BuildConfiguration)
            msbuildArguments: /t:publish /p:SignType=$(SignType) /p:SigningIdentity=$(SigningIdentity)
        - task: PowerShell@2
          displayName: Clean Build Dir
          inputs:
            filePath: $(Build.SourcesDirectory)/scripts/build/Clean-BuildDir.ps1
            arguments: -manifestDir $(Build.SourcesDirectory)/dist
        - task: PowerShell@2
          displayName: (Hack) Copy Signed bits
          inputs:
            filePath: $(Build.SourcesDirectory)/azure-pipelines/scripts/Copy-SignedBits.ps1
            arguments: -verbose
            errorActionPreference: continue
        - task: NuGetCommand@2
          displayName: NuGet restore for setup
          inputs:
            solution: installer/IISAdministrationSetup.sln
        - task: MSBuild@1
          displayName: Build Setup executable
          inputs:
            solution: installer/IISAdministrationSetup.sln
            msbuildVersion: 17.0
            msbuildArchitecture: x64
            platform: x64
            configuration: $(BuildConfiguration)
            msbuildArguments: /p:SignType=$(SignType)
        - task: PublishSymbols@2
          name: PublishSymbols8
          displayName: Index & Publish Symbols
          inputs:
            symbolsFolder: $(Build.SourcesDirectory)/dist/symbols
            searchPattern: '*.pdb'
            symbolServerType: TeamServices
        - task: ms-vseng.MicroBuildShipTasks.7c429315-71ba-4cb3-94bb-f829c95f7915.MicroBuildCodesignVerify@2
          displayName: Verify Signed Bits
          inputs:
            targetFolders: |
              $(Build.SourcesDirectory)/installer/IISAdministrationBundle/bin/x64/$(BuildConfiguration)
            whiteListPathForCerts: ./azure-pipelines/verify.signing/no_authenticode.txt
            excludeSNVerify: true