trigger:
  branches:
    include:
      - dev
      - master
      - preview/*
      - releases/*

pr:
  autoCancel: "false"
  branches:
    include:
      - dev
      - master
      - preview/*
      - releases/*

jobs:
- job: build
  pool:
    name: 'Hosted VS2017'  # name of the pool to run this job in
    demands:
      - msbuild
      - visualstudio
      - vstest
  steps:
    - checkout: self

    - task: NuGetToolInstaller@0
      inputs:
        versionSpec: '>=4.7.1'

    - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core sdk 2.1.505'
      inputs:
        version: 2.1.505

    - task: NuGetCommand@2
      displayName: 'Restore Dependencies'
      inputs:
        command: restore
        restoreSolution: '*.sln'

    - task: MSBuild@1
      displayName: 'Build IIS Administration'
      inputs:
        solution: Microsoft.IIS.Administration.sln
        msbuildVersion: "15.0"
        msbuildArchitecture: x64
        configuration: 'release'
        msbuildArguments: '/t:publish'

    - task: PowerShell@2
      displayName: 'PowerShell Script build.ps1'
      inputs:
        targetType: filePath
        filePath: ./build.ps1
        arguments: '-devSetup -install -test -verbose'
